using System.Net.Http.Headers;
using System.Text.Json;
using DevDigest.App.Models;
using Microsoft.Extensions.Logging;

namespace DevDigest.App.Services;

public interface IDeliveryService
{
    Task SendDigestEmailAsync(string toEmail, Dictionary<string, string> categorySummaries, CancellationToken cancellationToken = default);
}

public class DeliveryService : IDeliveryService
{
    private readonly SendGridSettings _sendGridSettings;
    private readonly ILogger<DeliveryService> _logger;
    private readonly HttpClient _httpClient;

    public DeliveryService(HttpClient httpClient, DigestConfig config, ILogger<DeliveryService> logger)
    {
        _httpClient = httpClient;
        _sendGridSettings = config.SendGrid;
        _logger = logger;
    }

    public async Task SendDigestEmailAsync(string toEmail, Dictionary<string, string> categorySummaries, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrEmpty(_sendGridSettings.ApiKey))
        {
            _logger.LogWarning("No SendGrid API key configured. Skipping email delivery.");
            return;
        }

        var htmlBody = GenerateHtmlEmail(categorySummaries);
        var subject = $"DevDigest - {DateTime.UtcNow:MMMM dd, yyyy}";

        var request = new
        {
            personalizations = new[]
            {
                new { to = new[] { new { email = toEmail } } }
            },
            from = new { email = _sendGridSettings.FromEmail, name = "DevDigest" },
            subject = subject,
            content = new[]
            {
                new { type = "text/html", value = htmlBody }
            }
        };

        var requestJson = JsonSerializer.Serialize(request);
        using var content = new StringContent(requestJson, System.Text.Encoding.UTF8, "application/json");

        using var message = new HttpRequestMessage(HttpMethod.Post, "https://api.sendgrid.com/v3/mail/send");
        message.Content = content;
        message.Headers.Authorization = new AuthenticationHeaderValue("Bearer", _sendGridSettings.ApiKey);

        using var response = await _httpClient.SendAsync(message, cancellationToken);
        
        if (!response.IsSuccessStatusCode)
        {
            var error = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new Exception($"Failed to send email via SendGrid: {error}");
        }

        _logger.LogInformation("Digest email sent successfully to {ToEmail}", toEmail);
    }

    private static string GenerateHtmlEmail(Dictionary<string, string> categorySummaries)
    {
        var categoriesHtml = string.Join("\n", categorySummaries.Select(kvp => $@"
        <div style='margin-bottom: 30px;'>
            <h2 style='color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px;'>
                {EscapeHtml(kvp.Key)}
            </h2>
            <div style='line-height: 1.8;'>
                {kvp.Value.Replace("\n", "<br/>")}
            </div>
        </div>
        "));

        return $@"<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <title>DevDigest</title>
</head>
<body style='font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; background-color: #f5f5f5;'>
    <div style='background-color: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 4px rgba(0,0,0,0.1);'>
        <h1 style='color: #2c3e50; text-align: center; margin-bottom: 10px;'>
            🚀 DevDigest
        </h1>
        <p style='text-align: center; color: #7f8c8d; margin-bottom: 30px;'>
            Your Daily Developer Newsletter - {DateTime.UtcNow:MMMM dd, yyyy}
        </p>
        {categoriesHtml}
        <div style='margin-top: 40px; padding-top: 20px; border-top: 1px solid #ecf0f1; text-align: center; color: #95a5a6; font-size: 12px;'>
            <p>Generated by DevDigest • Built with .NET 8</p>
        </div>
    </div>
</body>
</html>";
    }

    private static string EscapeHtml(string text)
    {
        return text
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;")
            .Replace("\"", "&quot;")
            .Replace("'", "&#39;");
    }
}