using MailKit.Net.Smtp;
using MailKit.Security;
using MimeKit;
using DevDigest.App.Models;
using Microsoft.Extensions.Logging;

namespace DevDigest.App.Services;

public interface IDeliveryService
{
    Task SendDigestEmailAsync(string toEmail, Dictionary<string, string> categorySummaries, CancellationToken cancellationToken = default);
}

public class DeliveryService : IDeliveryService
{
    private readonly EmailSettings _emailSettings;
    private readonly ILogger<DeliveryService> _logger;

    public DeliveryService(DigestConfig config, ILogger<DeliveryService> logger)
    {
        _emailSettings = config.Email;
        _logger = logger;
    }

    public async Task SendDigestEmailAsync(string toEmail, Dictionary<string, string> categorySummaries, CancellationToken cancellationToken = default)
    {
        var message = new MimeMessage();
        message.From.Add(new MailboxAddress("DevDigest", _emailSettings.Username));
        message.To.Add(new MailboxAddress(string.Empty, toEmail));
        message.Subject = $"DevDigest - {DateTime.UtcNow:MMMM dd, yyyy}";

        var htmlBody = GenerateHtmlEmail(categorySummaries);
        message.Body = new TextPart("html") { Text = htmlBody };

        using var client = new SmtpClient();
        
        await client.ConnectAsync(_emailSettings.SmtpHost, _emailSettings.SmtpPort, SecureSocketOptions.StartTls, cancellationToken);
        await client.AuthenticateAsync(_emailSettings.Username, _emailSettings.Password, cancellationToken);
        await client.SendAsync(message, cancellationToken);
        await client.DisconnectAsync(true, cancellationToken);

        _logger.LogInformation("Digest email sent successfully to {ToEmail}", toEmail);
    }

    private static string GenerateHtmlEmail(Dictionary<string, string> categorySummaries)
    {
        var categoriesHtml = string.Join("\n", categorySummaries.Select(kvp => $@"
        <div style='margin-bottom: 30px;'>
            <h2 style='color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px;'>
                {EscapeHtml(kvp.Key)}
            </h2>
            <div style='line-height: 1.8;'>
                {kvp.Value.Replace("\n", "<br/>")}
            </div>
        </div>
        "));

        return $@"<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <title>DevDigest</title>
</head>
<body style='font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; background-color: #f5f5f5;'>
    <div style='background-color: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 4px rgba(0,0,0,0.1);'>
        <h1 style='color: #2c3e50; text-align: center; margin-bottom: 10px;'>
            🚀 DevDigest
        </h1>
        <p style='text-align: center; color: #7f8c8d; margin-bottom: 30px;'>
            Your Daily Developer Newsletter - {DateTime.UtcNow:MMMM dd, yyyy}
        </p>
        {categoriesHtml}
        <div style='margin-top: 40px; padding-top: 20px; border-top: 1px solid #ecf0f1; text-align: center; color: #95a5a6; font-size: 12px;'>
            <p>Generated by DevDigest • Built with .NET 8</p>
        </div>
    </div>
</body>
</html>";
    }

    private static string EscapeHtml(string text)
    {
        return text
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;")
            .Replace("\"", "&quot;")
            .Replace("'", "&#39;");
    }
}